### ISSUE TITLE
Build error TS2314: Generic type 'ComponentFixture<T>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by lpenet** [wkwiatek/angular2-webpack#3]
When I do :
`
npm install
npm run build
`

I get the following error :
``

> angular2-webpack@1.0.0 build /mnt/ssd/home_bis/devoss/angular2-webpack2
> WEBPACK_ENV=production webpack --progress --hide-modules

 10% building modules 0/2 modules 2 active ...ss/angular2-webpack2/src/bootstrap.tsts-loader: Using typescript@1.8.10 and /mnt/ssd/home_bis/devoss/angular2-webpack2/tsconfig.json
Hash: 20280117b304531f65b1  
Version: webpack 2.1.0-beta.7
Time: 14104ms
     Asset       Size  Chunks             Chunk Names
 vendor.js     517 kB       0  [emitted]  vendor
    app.js     663 kB       1  [emitted]  app
index.html  224 bytes          [emitted]  

ERROR in /mnt/ssd/home_bis/devoss/angular2-webpack2/src/app.spec.ts
(29,57): error TS2314: Generic type 'ComponentFixture<T>' requires 1 type argument(s).

npm ERR! Linux 4.4.0-1-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.6.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack@1.0.0 build: `WEBPACK_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular2-webpack@1.0.0 build script 'WEBPACK_ENV=production webpack --progress --hide-modules'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     WEBPACK_ENV=production webpack --progress --hide-modules
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack
npm ERR! There is likely additional logging output above.

``

**Comment by wkwiatek** [comment]
@lpenet Should be fixed with most recent commit. Thanks for pointing that out!
