### ISSUE TITLE
Can not build dev

### ISSUE THREAD

**Issue by lemacabre** [wkwiatek/angular2-webpack#8]
Hi,
I tried to run the dev mode and the prod build but I got the following error message:

> WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
> 45:15 Critical dependency: the request of a dependency is an expression
> 
> WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
> 57:15 Critical dependency: the request of a dependency is an expression
> 
> ERROR in ./src/bootstrap.ts
> (23,5): error TS2304: Cannot find name 'RouterModule'.
> 
> ERROR in ./src/vendor.ts
> Module not found: Error: Can't resolve 'es6-shim' in '/home/lemacabre/projekte/angular2/angular2-webpack2/src'
>  @ ./src/vendor.ts 6:0-19
>  @ multi vendor
> webpack: bundle is now VALID.

I tried it with linux.

**Comment by wkwiatek** [comment]
It's fixed now. Thanks for reporting!

**Comment by wkwiatek** [comment]
It's fixed now. Thanks for reporting!
